sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.coveragePlugin=jacoco
sonar.coverage.exclusions=\
src/main/java/com/innowise/authenticationservice/config/**,\
src/main/java/com/innowise/authenticationservice/exception/**,\
src/main/java/com/innowise/authenticationservice/model/**